---
title: "Calcite Analysis"
author: "S. Eanes"
date: "11/28/2020"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r import, warning=F, include=F}
library(tidyverse)
library(gridExtra)
```

## Setup data

```{r data}
coral <- read.csv("~/School/Fossil Coral/data/coral_3weighted.csv")

#omit data with no response
coral <- coral[!is.na(coral$U238),]


#select three largest species
genus_trim <- c("Acropora", "Porites")
#remove coral with age > 10
coral <- coral[which(coral$Genus %in% genus_trim),]  %>% dplyr::filter(Age < 10)

#clean up a nice dataframe
coral.df <- coral %>% mutate(Temperature = Temp,
                             Calcite = ifelse(is.na(Calcite),"N/A",ifelse(Calcite>1,"Calcite>1","Calcite<=1"))) %>%
  select(U238,pH,TAlk,Salinity,Temperature,OmegaA,TCO2,Calcite) %>%
  data.frame()

coral.df$U238 <- coral.df$U238 * 0.421
nrow(coral.df)

```

```{r}
library(corrplot)
coral.corr <- coral.df %>% rename( Temp = Temperature, Omega = OmegaA) %>% select(-Calcite)
corrplot.mixed(cor(coral.corr),lower.col="black")

```

```{r}
f1 <- ggplot(coral.df, aes(pH,U238))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~Calcite)


f2 <- ggplot(coral.df, aes(Temperature,U238))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~Calcite)


f3 <- ggplot(coral.df, aes(Salinity,U238))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~Calcite)


f4 <- ggplot(coral.df, aes(OmegaA,U238))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~Calcite)


f5 <- ggplot(coral.df, aes(TCO2,U238))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~Calcite)


f6 <- ggplot(coral.df, aes(TAlk,U238))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~Calcite)

grid.arrange(f1,f2,f3,f4,f5,f6,ncol=2)
  
```

## Figure A1 $R^2$

```{r}
df1 <- coral.df[coral.df$Calcite=="Calcite<=1",]
df2 <- coral.df[coral.df$Calcite=="Calcite>1",]
df3 <- coral.df[coral.df$Calcite=="N/A",]
nrow(df1)+nrow(df2)+nrow(df3)

#use adj.r.squared for adjusted instead of regular r squared

#temp
summary(lm(U238 ~ Temperature, data=df1))$r.squared
summary(lm(U238 ~ Temperature, data=df2))$r.squared
summary(lm(U238 ~ Temperature, data=df3))$r.squared

#ph
summary(lm(U238 ~ pH, data=df1))$r.squared
summary(lm(U238 ~ pH, data=df2))$r.squared
summary(lm(U238 ~ pH, data=df3))$r.squared

#salinity
summary(lm(U238 ~ Salinity, data=df1))$r.squared
summary(lm(U238 ~ Salinity, data=df2))$r.squared
summary(lm(U238 ~ Salinity, data=df3))$r.squared

#omega
summary(lm(U238 ~ OmegaA, data=df1))$r.squared
summary(lm(U238 ~ OmegaA, data=df2))$r.squared
summary(lm(U238 ~ OmegaA, data=df3))$r.squared

#tco2
summary(lm(U238 ~ TCO2, data=df1))$r.squared
summary(lm(U238 ~ TCO2, data=df2))$r.squared
summary(lm(U238 ~ TCO2, data=df3))$r.squared

#Talk
summary(lm(U238 ~ TAlk, data=df1))$r.squared
summary(lm(U238 ~ TAlk, data=df2))$r.squared
summary(lm(U238 ~ TAlk, data=df3))$r.squared
```

